### ISSUE TITLE
transform: append-only

### ISSUE THREAD

**Issue by awb99** [clojure-quant/quanta-bar-warehouse#1]
Transform-append-only ist so wie transform: compress zu schreiben.

- zuerst laedt er die bestehende zeitreihe.
- dann ermittelt er, die letzte bestehende bar
- dann requested er das intervall von letzte-bestehende+1bar bis window-end
- wenn daten gekommen sind, fuegt er dem bestehende-ds das request-result-ds
hinzu und liefert das als resultat zurueck.

**Comment by wizard50** [comment]
done by using
- bardb
- importer
- forwarding to compression transform
